### ISSUE TITLE
Essential theme screenshots in various browsers

### ISSUE THREAD

**Issue by ndenmeade** [eduridden/moodle-theme_essential#9] opened 2013-06-09 03:14 UTC
The Essential theme looks great across a wide range of devices, see attached zip file for 22 browser shots. 
https://dl.dropboxusercontent.com/u/33611569/essential_screenshot.zip

Is there an upgrade due to Essential theme to be released soon? There are a few bugs that have surfaced
1. The slider needs to be hidden on very narrow layouts
2.  IE 8 and 9 have some issues with the nav bar.. IE 7 ..well we wont talk about that. 
3. Drop down menu Z order and/or links not working
4. Text editor (been discussed elsewhere)
5. Awesome font fails to load in Mobiles, Safari and iOS. See these articles as it is a common error with this font
      http://stackoverflow.com/questions/15399409/fontawesome-loading-but-not-displaying-in-chrome-safari-or-firefox-displays-sm
   
      http://stackoverflow.com/questions/15028602/font-awesome-icons-are-not-working-in-some-browsers
   
     https://github.com/netdna/bootstrap-cdn/issues/27

**Comment by martygilbert** [comment] 2013-07-05 13:39
Love this theme! We hope to use it in the fall for classes, if it gets production ready.

I second #2 above. The IE nav bar issue is a big one, unfortunately, because our institution only officially supports IE. 

Keep up the good work!

**Comment by seasharp** [comment] 2013-07-16 21:50
First off let me say great job on the theme, I love it.  It is a giant leap up from the other themes on Moodle.

I do have the same issue as #2 listed above, I took a look at the IE developer tools and determined that the issue is caused by the following line of code within the css:

.navbar-inner
{
     filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#ffffffff',endColorstr='#fff2f2f2',GradientType=0);
}

To fix the issue you can comment out this line in the theme/bootstrapbase/style/moodle.css file.  I am not sure if this change will be overwritten by LESS or not, but commenting it out worked for me.  If a better solution is found please post for others to see.

**Comment by eduridden** [comment] 2013-07-16 23:51
Sadly as the bootstrap base theme is something I cannot fix I can't implement in my theme to fix :(

**Comment by ndenmeade** [comment] 2013-07-17 06:13
We did resolve all of the issues listed above and our nav bar is working in IE 10. You can see the results ( and copy out the code fixes) at http://online.evet.qld.edu.au/

We emailed our code to Julian, so the latest version of Essential theme may include some of our changes.

I am really happy with how our theme turned out and am excited to see how it will be used by other institutes.

**Comment by utlc** [comment] 2013-07-26 04:11
Good Day ndenmeade,
can i have your code to fixed bug number 2 only ?
Or u can teach me to fix it
Thanks for your help

**Comment by eduridden** [comment] 2013-07-30 09:06
The code from ndenmeade is merged into the Essential core.

**Comment by martygilbert** [comment] 2013-08-01 15:41
I'm still experiencing the IE nav bar issue with today's MOODLE_253 branch. 

Perhaps the changes by ndenmeade weren't merged or weren't provided? 

ndenmeade, perhaps you could let us know how you fixed the IE nav bar issue?

Many thanks to all for their hard work, especially Julian.

**Comment by utlc** [comment] 2013-08-13 03:20
Hi, Good Day
I got a icon problem here in IE 8/9
How to fix this ?
![1](https://f.cloud.github.com/assets/5094054/952255/418e911c-03c7-11e3-80f0-efaee4b86b56.JPG)

**Comment by seasharp** [comment] 2013-08-20 18:11
Marty,

In the custom.css file find the class '.navbar .inner' and make sure it has the filter property set to none.  This is what took care of my navbar issue.

**Closed as completed** 2013-10-13 10:27 UTC

**Comment by fabricioflores** [comment] 2013-11-20 13:57
Hi. I tested in my iPhone your site http://online.evet.qld.edu.au/ and it stills has the error (3). The dropdown menu doesn't show in iPhone in portrait orientation. I have a screenshot of this.
![la foto 2](https://f.cloud.github.com/assets/3495122/1582285/afe01c36-51eb-11e3-839e-83506c6996c7.PNG)
![la foto 1](https://f.cloud.github.com/assets/3495122/1582286/aff7c4b2-51eb-11e3-8c42-8dbe1efe68d6.PNG)
