### ISSUE TITLE
frontpage.php 

### ISSUE THREAD

**Issue by mattrice** [eduridden/moodle-theme_essential#51] opened 2013-08-13 20:39 UTC
There should be a div close tag right about line 370 to stop the page div from encompassing the footer.

**Comment by eduridden** [comment] 2013-08-23 13:18
The page div is intentionally encompassing the footer. Some users who are using dark background images have wanted to add a color to the #page class and have it encompass the whole area. This is closed as not a bug.

**Closed as completed by eduridden** 2013-08-23 13:18 UTC
